01-cli
niksaz/spbau-software-design pull request #1
Opened 2018-02-24 18:56 UTC by niksaz

2018-02-25 18:10 UTC, yurii-litvinov requested changes
В общем-то, практически всё хорошо. Не работает `echo ololo | cat`, потому что cat всегда ожидает аргумента, тогда как хотелось бы, чтобы если аргумента нет, она бы просто печатала входной поток (как настоящий cat). Ещё `echo 123 | wc` выдаёт 1 1 5, тогда как настоящий wc на таком тесте выдаёт 1 1 4 (ответ 1 1 3 тоже пойдёт, но 1 1 5 как-то совсем странно).

Ещё  почти все тесты не проходят под виндой из-за, внезапно, различий в символах перевода строки. Тесты ожидают \n, но программа выдаёт \r\n.

По архитектуре единственное замечание --- Cli создаёт Repl, но поскольку Cli ещё и играет роль CommandPrompter, Repl вынужден про него помнить и время от времени дёргать. Можно было бы CommandPrompter сделать отдельным классом, который бы Cli просто отдавала Repl-у.

Ещё всё-таки хотелось бы небольшого текста про то, как всё устроено. Никакая диаграма не заменит документации. Хотя бы в виде более обзорных комментариев в коде (Scala же имеет какой-нибудь аналог package-info.java?). Или в README немного расписать.

2018-02-25 18:10 UTC, yurii-litvinov commented on 01-cli/src/main/scala/Cli.scala
> +import java.io.ByteArrayInputStream
Надо бы ещё корневой пакет для всего проекта, классы без пакета --- как-то не очень

2018-02-25 18:10 UTC, yurii-litvinov commented on 01-cli/src/main/scala/model/Environment.scala
> +    commandRunners: List[CommandRunner]) extends VariableSupplier {
Неожиданно, что список команд --- именно список. В processCommand приходится обходить его весь, чтобы найти команду для исполнения.

2018-02-25 18:33 UTC, niksaz commented
"Ещё echo 123 | wc выдаёт 1 1 5, тогда как настоящий wc на таком тесте выдаёт 1 1 4 (ответ 1 1 3 тоже пойдёт, но 1 1 5 как-то совсем странно)"
@yurii-litvinov, погодите, а разве это некорректно? 
echo 123 выдает на windows "123\r\n", что и есть 5 байт. Вроде никак иначе. На Unix 1 1 4 получаем.

2018-02-25 18:55 UTC, yurii-litvinov commented
Аа, ну в этом есть своя логика. Тогда ладно, считаем, что с `echo 123 | wc` всё ок

2018-02-25 19:02 UTC, niksaz commented
Ага, спасибо Вам за пояснения и замечания!

2018-02-28 15:18 UTC, yurii-litvinov approved these changes
Окей, зачтена. Пара тестов под винду всё равно не проходит, и документация всё-таки не очень, но для первой задачи вполне достаточно.

2018-02-28 15:18 UTC, yurii-litvinov commented on 01-cli/src/main/scala/shell/process/SequentialCommandProcessor.scala
> +      if (name == args.head) {
Хм, а в чём тогда смысл Map? :)

2018-02-28 15:18 UTC, yurii-litvinov commented on 01-cli/src/main/scala/shell/package.scala
> +  * Package contains classes to provide command line interface functionality.
Тут бы ещё описать кратко подпакеты и их взаимодействие. Сейчас человек, который приходит в проект со стороны, не имеет ничего, что помогло бы ему разобраться с архитектурой, кроме структуры кода. Для CLI это не важно, потому что весь код можно прочитать за час, но если бы в системе была пара миллионов строк, несчастный вынужден был бы прочитать несколько тысяч таких вот комментариев с описанием пакета, чтобы хоть примерно понять, что к чему. Я хотел общее описание в духе "а тут у нас подсистема ввода, там команды, они общаются так-то, за подробностями туда". Диаграмма не соответствует структуре пакетов, поэтому не очень помогает.

2018-02-28 20:57 UTC, niksaz commented on 01-cli/src/main/scala/shell/process/SequentialCommandProcessor.scala
> +      if (name == args.head) {
Справедливое замечание. ;)

2018-02-28 20:58 UTC, niksaz commented on 01-cli/src/main/scala/shell/package.scala
> +  * Package contains classes to provide command line interface functionality.
Да, все же без отдельного ~документа не обойтись.

2018-02-28 21:02 UTC, merged