01-cli-grep
niksaz/spbau-software-design pull request #2
Opened 2018-03-22 19:05 UTC by niksaz

2018-04-21 15:39 UTC, yurii-litvinov requested changes
- Опция -w не работает:
```
> grep -w scalaVers build.sbt
scalaVersion := "2.12.2"
```
Поправьте, пожалуйста

2018-04-21 15:39 UTC, yurii-litvinov commented on 01-cli/src/main/scala/shell/command/GrepCommandRunner.scala
> +      case t: Throwable => System.err.println(s"grep: ${t.getMessage}")
Ловить Throwable как-то не очень

2018-04-21 18:41 UTC, niksaz commented on 01-cli/src/main/scala/shell/command/GrepCommandRunner.scala
> +      case t: Throwable => System.err.println(s"grep: ${t.getMessage}")
Зато надежно. (: Подравил, спасибо.

2018-04-21 18:42 UTC, niksaz commented
Действительно, понимание мое разошлось с описанием того, что делает `grep -w`. Благодарю за замечание.

2018-04-22 10:59 UTC, yurii-litvinov approved these changes
Ага, теперь всё ок, зачтена

2018-04-22 12:04 UTC, merged