Implemented ls and cd commands
niksaz/spbau-software-design pull request #3
Opened 2018-03-23 18:13 UTC by Denzed

2018-04-21 16:38 UTC, yurii-litvinov requested changes
Команды реализованы, но из REPL-а недоступны :) Кроме того, 
- Вывод в духе `...01-cli\.\build.sbt` довольно странный --- путей "." вообще в выдаче ls быть не должно, по идее. И не надо показывать полный путь, по умолчанию ls так не делает, надо только имена файлов и папок
- Сейчас имён папок в выдаче ls вообще нет
- 
```
> cd ../../..
> ls
C:\Students\302\CD-LS\Denzed-Software-Design-6th-semester-task4\01-cli\src\..\src\main\scala\shell\..\..\..\.:
```
Этак через некоторое количество операций cd нас ждёт фэйл :)

Поправьте, пожалуйста.

2018-04-21 16:38 UTC, yurii-litvinov commented on 01-cli/src/main/scala/shell/command/CdCommandRunner.scala
> +      case _ => throw new Exception("Too many arguments")
Лучше кидать более специфичное исключение

2018-04-22 18:17 UTC, Denzed commented on 01-cli/src/main/scala/shell/command/CdCommandRunner.scala
> +      case _ => throw new Exception("Too many arguments")
Поменял на IllegalArgumentException

2018-04-28 13:37 UTC, yurii-litvinov approved these changes
Теперь всё отлично, зачтена

2018-05-01 18:49 UTC, merged